name: "Lint and Build"

on:
  merge_group:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          cache: npm
          node-version: '24'
      - run: npm ci
      - name: Run depcheck
        run: npm run depcheck
      - run: npm run lint
      - run: npm run build
      - name: Ensure PR is not on main branch
        uses: jaegertracing/jaeger/.github/actions/block-pr-from-main-branch@main
