name: "Unit Tests"

on:
  merge_group:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          cache: npm
          node-version: '24'
      - run: npm ci
      - run: npm ls --all
      - run: npm run coverage
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          fail_ci_if_error: true
          verbose: true
          # Using upload token helps against rate limiting errors.
          # Cannot define it as secret as we need it accessible from forks.
          # See https://github.com/codecov/codecov-action/issues/837
          token: 31c3122b-7b49-4267-a117-8c9354a97119
